Ishwor Chalise

4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [74]:
#Q.1
import numpy as np

# Task 1: Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:\n", empty_array)


Empty Array:
 [[1. 0.]
 [0. 1.]]


In [75]:
# Task 2: Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array:\n", ones_array)



All Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [76]:
# Task 3: Return a new array of given shape and type, filled with fill value
filled_array = np.full((3, 3), 7)
print("\nArray Filled with 7:\n", filled_array)


Array Filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Task 4: Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Like Given Array:\n", zeros_like_array)


Zeros Like Given Array:
 [[0 0 0]
 [0 0 0]]


In [78]:
# Task 5: Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Like Given Array:\n", ones_like_array)


Ones Like Given Array:
 [[1 1 1]
 [1 1 1]]


In [79]:
# Task 6: Convert a list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted Numpy Array:\n", numpy_array)



Converted Numpy Array:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [80]:
import numpy as np

# Task 1: Create an array with values ranging from 10 to 49
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)


Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [81]:

# Task 2: Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)



3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [82]:
# Task 3: Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:
# Task 4: Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array:\n", random_array)
print("Mean of Random Array:", mean_value)


Random Array:
 [0.04522888 0.46065036 0.58952574 0.93962672 0.25357791 0.02865956
 0.07016496 0.9741803  0.32564982 0.404682   0.82219669 0.25618483
 0.53200526 0.14951901 0.88993612 0.65982644 0.55407029 0.81315952
 0.9227617  0.89482797 0.49444601 0.6876458  0.39463894 0.0942156
 0.9039569  0.2095305  0.0105044  0.78747324 0.02025453 0.70388752]
Mean of Random Array: 0.49643291707649406


In [84]:
# Task 5: Create a 10x10 array with random values and find the min and max values
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


10x10 Random Array:
 [[0.56221184 0.27222846 0.1514027  0.11103939 0.63245218 0.1971435
  0.48386058 0.10664939 0.28887963 0.82314524]
 [0.16383436 0.2652833  0.92094549 0.31198862 0.538905   0.25130603
  0.5157706  0.27097792 0.1571166  0.71168896]
 [0.28374481 0.58713559 0.4047306  0.1055456  0.83152179 0.46580354
  0.43372092 0.21550442 0.19753694 0.08317178]
 [0.69679488 0.43811493 0.34429744 0.07557162 0.49375802 0.90831873
  0.33839699 0.62628539 0.69017055 0.307926  ]
 [0.21039515 0.68441084 0.2177687  0.25355365 0.88925669 0.13673581
  0.03497316 0.20173015 0.7111794  0.43419394]
 [0.95422588 0.12607452 0.96172773 0.84840668 0.91651694 0.78839002
  0.13017045 0.29938794 0.97425696 0.17210571]
 [0.52927259 0.41716763 0.96233492 0.07031976 0.90743085 0.68923622
  0.4477161  0.79164875 0.73288708 0.57843639]
 [0.03400892 0.92324521 0.51865374 0.57882641 0.93011387 0.81915134
  0.55740435 0.9872849  0.51643665 0.32137585]
 [0.09301007 0.2673383  0.66137609 0.29189635 0.5221203  0.

In [85]:
# Task 6: Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1 
print("\nZero Array with 5th element as 1:\n", zero_array)


Zero Array with 5th element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [86]:
# Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = [1, 2, 0, 0, 4, 0]
reversed_array = np.array(arr)[::-1]
print("\nReversed Array:\n", reversed_array)


Reversed Array:
 [0 4 0 0 2 1]


In [87]:
# Task 8: Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5)) 
border_array[1:-1, 1:-1] = 0
print("\n2D Array with Border of 1 and Inside 0:\n", border_array)


2D Array with Border of 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [88]:
# Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1 
checkerboard[::2, 1::2] = 1     
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add 
addition = x + y
print("Addition of x and y:\n", addition)

# 2. Subtract
subtraction = x - y
print("Subtraction of x and y:\n", subtraction)

# 3. Multipal the array with any integer 
multiplied = x * 3
print("x multiplied by 3:\n", multiplied)

# 4. Find the square of each element of the array
square = np.square(x)
print("Square of elements in x:\n", square)

# 5. Dot products
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:\n", dot_x_v)
print("Dot product of x and y:\n", dot_x_y)

# 6. Concatenate x and y along rows, and v and w along columns
concat_x_y = np.concatenate((x, y), axis=0)
concat_v_w = np.vstack((v, w))
print("Concatenation of x and y along rows:\n", concat_x_y)
print("Concatenation of v and w along columns:\n", concat_v_w)

# 7. Concatenate x and v
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("Concatenation of x and v:\n", concat_x_v)
except ValueError as e:
    print("Error during concatenation of x and v:", e)


Addition of x and y:
 [[ 6  8]
 [10 13]]
Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]
x multiplied by 3:
 [[ 3  6]
 [ 9 15]]
Square of elements in x:
 [[ 1  4]
 [ 9 25]]
Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]
Error during concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [90]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I
A_inv = np.linalg.inv(A)  
identity_matrix = np.dot(A, A_inv)  
print("A * A^(-1):\n", identity_matrix)

# Check it's approximately equal to the identity matrix
print("Is A * A^(-1) approximately the identity matrix? ", np.allclose(identity_matrix, np.eye(A.shape[0])))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", np.array_equal(AB_T, BT_AT))

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

# AX = B
A_matrix = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])
B_vector = np.array([-1, -3, 9])

# using the inverse method
A_inv_matrix = np.linalg.inv(A_matrix)
X = np.dot(A_inv_matrix, B_vector)
print("Solution using inverse method (X):\n", X)

# using np.linalg.solve 
X_solve = np.linalg.solve(A_matrix, B_vector)
print("Solution using np.linalg.solve (X):\n", X_solve)


A * A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A^(-1) approximately the identity matrix?  True
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal?  False
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T?  True
Solution using inverse method (X):
 [ 2.  1. -2.]
Solution using np.linalg.solve (X):
 [ 2.  1. -2.]
